version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8.10
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            pip install --upgrade pip
            pip install tox
            tox